### ISSUE TITLE
Docs WG merger

### ISSUE THREAD

**Issue by ferd** [erlef/build-and-packaging-wg#13]
# Background 

Tooling work is all that’s left for the docs folks, so we should be folding the group within this WG's efforts.

# Tasks

- [x] Provide the list of people coming over
- [x] Sync with the board to announce and make the change official
- [x] Update the charter and invite lists to events

# Related agenda items, issues, and pull requests. 

 - [Feb 5 in the old agenda](https://docs.google.com/document/d/1neU4faTXVA3pz2CMuzIhN-nqrFsPfzO-QhBGdGdbHUU/edit#heading=h.s3wr64ye5d4)
