### ISSUE TITLE
Implement hex web auth flow

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#21]
# Background 

Per #18 we have agreed to move forward with implementing a web auth token flow implemented in hex.pm and utilized by  mix hex and rebar3_hex. 

# Tasks

The following tasks must be completed to resolve this issue. 

- [ ] Add this project to the gsoc roster for 2021 (https://github.com/erlef/gsoc)  
- [ ] Complete action item #11 
- [ ] Create an issue on hexpm to align on flow and low level specifications
- [ ] Create an issue on hex_core to support the new api that will be described and detailed in the above task
- [ ] Create an issue on mix hex for working the new hex_core api offerings into to mix hex
- [ ] Create an issue on rebar3_hex for working the new hex_core api offerings into rebar3_hex
- [ ] Work with gsoc mentees and mentors to esolve all issues above

# Related agenda items, issues, and pull requests.

**Comment by starbelly** [comment]
Just to note, I've neglected this, but purposefully. There should be a new mentors group and our plans for GSOC for these things might do well in there. That said, I wouldn't want to wait a long time before doing this.

**Comment by wojtekmach** [comment]
I have added an issue to Hex.pm: https://github.com/hexpm/hexpm/issues/1024 that hopefully gives some more context. It doesn't have a detailed specification, such would hopefully be created as part of working on a proof-of-concept.
