### ISSUE TITLE
Retire the eef build and packaging channel on erlanger

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#23]
# Background 

We have opened up the eef slack to all members. As such, it doesn't make a lot of sense to keep the B&P channel around on erlanger, not for terribly long anyway. I think we should keep it around for a while, but set the topic and/or description to "Join us on eef slack" 

# Tasks

The following tasks must be completed to resolve this issue. 

- [ ] Get consensus on the issue 
- [ ] Set an appropriate topic and/or description on erlanger B&P channel
- [ ] Set a date for hard deprecating the channel

**Comment by paulo-ferraz-oliveira** [comment]
Just a thought: would it be terribly bad to make the channel private (this way the people there stay there, but you stop new people from coming in)? I'm not sure it can be private and searchable (so that the description could say "We've migrated to EEF's Slack. Join us there!").

In any case, maybe letting people know the other one exists and slowly drain this one could suffice.

As for deprecating the channel, does it hold content that would warrant it being archived?

---

**Edit**: I know this is probably a per-workgroup thing, but would it be possible to (after discussion is had here and consensus - or some sort of direction - reached) to propose the other wg to do the same?

**Comment by starbelly** [comment]
> Just a thought: would it be terribly bad to make the channel private (this way the people there stay there, but you stop new people from coming in)? I'm not sure it can be private and searchable (so that the description could say "We've migrated to EEF's Slack. Join us there!").

I'm not in favor of this. I'd rather have people join and then pointed in the right direction. Not everyone is aware that you can get an invite to eef slack or that it exists. 

> In any case, maybe letting people know the other one exists and slowly drain this one could suffice.

That's the idea.

> As for deprecating the channel, does it hold content that would warrant it being archived?

No, because it's not a paid slack everything is ephemeral. 

 > Edit: I know this is probably a per-workgroup thing, but would it be possible to (after discussion is had here and consensus - or some sort of direction - reached) to propose the other wg to do the same?
 
 That would be nice 😁 I can certainly try to work with other working groups after our discussion, but in the end, yes it is up to the group.

**Comment by josevalim** [comment]
In the meeting today we all agreed (or rather nobody disagreed) that we should retire the build and packaging channel on erlanger.

**Comment by starbelly** [comment]
Sounds good!

**Comment by starbelly** [comment]
@josevalim To clarify, no date heads up? Just close?

**Comment by josevalim** [comment]
Leave a note for a while and then close :)

**Comment by starbelly** [comment]
Ok, let's say 1 month from now. I will close this issue and open an action item ❤️

**Comment by starbelly** [comment]
Already closed this, but channel is now closed, may the 4th be with you!

**Comment by paulo-ferraz-oliveira** [comment]
@pablocostass ⬆️ he did it!
