### ISSUE TITLE
Add support for cookie path kernel argument in Erlang/OTP

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#62]
# Background 

In order to mitigate "leakage" of erlang cookies in an operating environment for an erlang application, a kernel argument should be added to erlang/otp such that one can provide a path to a cookie. 

# Tasks

The following tasks must be completed to resolve this issue. 

- [ ] Open up an issue on Erlang/OTP to get official buy-in for the feature
- [ ] Implement kernel argument for passing a path to a cookie 
- [ ] Open up an issue on Elixir to get official buy-in for supporting this feature
- [ ] Implement support for the feature

**Comment by starbelly** [comment]
There is no feedback on this and in retrospect this wouldn't be terribly great. It might encourage others to treat cookies like a security mechanism, and it is definitely not that.
